// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: olympus/foundation/v1/foundation.proto

package foundationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Vault Messages
type VaultReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultReadRequest) Reset() {
	*x = VaultReadRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadRequest) ProtoMessage() {}

func (x *VaultReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadRequest.ProtoReflect.Descriptor instead.
func (*VaultReadRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{0}
}

func (x *VaultReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type VaultReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultReadResponse) Reset() {
	*x = VaultReadResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadResponse) ProtoMessage() {}

func (x *VaultReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadResponse.ProtoReflect.Descriptor instead.
func (*VaultReadResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{1}
}

func (x *VaultReadResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VaultReadResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VaultWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultWriteRequest) Reset() {
	*x = VaultWriteRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWriteRequest) ProtoMessage() {}

func (x *VaultWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWriteRequest.ProtoReflect.Descriptor instead.
func (*VaultWriteRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{2}
}

func (x *VaultWriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultWriteRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VaultWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultWriteResponse) Reset() {
	*x = VaultWriteResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWriteResponse) ProtoMessage() {}

func (x *VaultWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWriteResponse.ProtoReflect.Descriptor instead.
func (*VaultWriteResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{3}
}

func (x *VaultWriteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VaultWriteResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Identity Messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyTokenRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyTokenResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

// IAM Messages
type TestIAMPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIAMPolicyRequest) Reset() {
	*x = TestIAMPolicyRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIAMPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIAMPolicyRequest) ProtoMessage() {}

func (x *TestIAMPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIAMPolicyRequest.ProtoReflect.Descriptor instead.
func (*TestIAMPolicyRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{8}
}

func (x *TestIAMPolicyRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *TestIAMPolicyRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TestIAMPolicyRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type TestIAMPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIAMPolicyResponse) Reset() {
	*x = TestIAMPolicyResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIAMPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIAMPolicyResponse) ProtoMessage() {}

func (x *TestIAMPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIAMPolicyResponse.ProtoReflect.Descriptor instead.
func (*TestIAMPolicyResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{9}
}

func (x *TestIAMPolicyResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *TestIAMPolicyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LookupIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupIdentityRequest) Reset() {
	*x = LookupIdentityRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIdentityRequest) ProtoMessage() {}

func (x *LookupIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIdentityRequest.ProtoReflect.Descriptor instead.
func (*LookupIdentityRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{10}
}

func (x *LookupIdentityRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LookupIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceAccount string                 `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Roles          []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookupIdentityResponse) Reset() {
	*x = LookupIdentityResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIdentityResponse) ProtoMessage() {}

func (x *LookupIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIdentityResponse.ProtoReflect.Descriptor instead.
func (*LookupIdentityResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{11}
}

func (x *LookupIdentityResponse) GetServiceAccount() string {
	if x != nil {
		return x.ServiceAccount
	}
	return ""
}

func (x *LookupIdentityResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *LookupIdentityResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

// KMS Messages
type KMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KMSRequest) Reset() {
	*x = KMSRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KMSRequest) ProtoMessage() {}

func (x *KMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KMSRequest.ProtoReflect.Descriptor instead.
func (*KMSRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{12}
}

func (x *KMSRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KMSRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type KMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KMSResponse) Reset() {
	*x = KMSResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KMSResponse) ProtoMessage() {}

func (x *KMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KMSResponse.ProtoReflect.Descriptor instead.
func (*KMSResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{13}
}

func (x *KMSResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type KMSSignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Digest        []byte                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KMSSignRequest) Reset() {
	*x = KMSSignRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KMSSignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KMSSignRequest) ProtoMessage() {}

func (x *KMSSignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KMSSignRequest.ProtoReflect.Descriptor instead.
func (*KMSSignRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{14}
}

func (x *KMSSignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *KMSSignRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type KMSSignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KMSSignResponse) Reset() {
	*x = KMSSignResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KMSSignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KMSSignResponse) ProtoMessage() {}

func (x *KMSSignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KMSSignResponse.ProtoReflect.Descriptor instead.
func (*KMSSignResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{15}
}

func (x *KMSSignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Database Auth Messages
type DBTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBTokenRequest) Reset() {
	*x = DBTokenRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBTokenRequest) ProtoMessage() {}

func (x *DBTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBTokenRequest.ProtoReflect.Descriptor instead.
func (*DBTokenRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{16}
}

func (x *DBTokenRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *DBTokenRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DBTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBTokenResponse) Reset() {
	*x = DBTokenResponse{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBTokenResponse) ProtoMessage() {}

func (x *DBTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBTokenResponse.ProtoReflect.Descriptor instead.
func (*DBTokenResponse) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{17}
}

func (x *DBTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DBTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ImpersonateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InstigatorIdentity   string                 `protobuf:"bytes,1,opt,name=instigator_identity,json=instigatorIdentity,proto3" json:"instigator_identity,omitempty"`
	TargetServiceAccount string                 `protobuf:"bytes,2,opt,name=target_service_account,json=targetServiceAccount,proto3" json:"target_service_account,omitempty"`
	Scopes               []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImpersonateRequest) Reset() {
	*x = ImpersonateRequest{}
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonateRequest) ProtoMessage() {}

func (x *ImpersonateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_foundation_v1_foundation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonateRequest.ProtoReflect.Descriptor instead.
func (*ImpersonateRequest) Descriptor() ([]byte, []int) {
	return file_olympus_foundation_v1_foundation_proto_rawDescGZIP(), []int{18}
}

func (x *ImpersonateRequest) GetInstigatorIdentity() string {
	if x != nil {
		return x.InstigatorIdentity
	}
	return ""
}

func (x *ImpersonateRequest) GetTargetServiceAccount() string {
	if x != nil {
		return x.TargetServiceAccount
	}
	return ""
}

func (x *ImpersonateRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

var File_olympus_foundation_v1_foundation_proto protoreflect.FileDescriptor

const file_olympus_foundation_v1_foundation_proto_rawDesc = "" +
	"\n" +
	"&olympus/foundation/v1/foundation.proto\x12\x15olympus.foundation.v1\"$\n" +
	"\x10VaultReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"C\n" +
	"\x11VaultReadResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\";\n" +
	"\x11VaultWriteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"H\n" +
	"\x12VaultWriteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"E\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"&\n" +
	"\x12CreateUserResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"/\n" +
	"\x12VerifyTokenRequest\x12\x19\n" +
	"\bid_token\x18\x01 \x01(\tR\aidToken\"=\n" +
	"\x13VerifyTokenResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\"f\n" +
	"\x14TestIAMPolicyRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"I\n" +
	"\x15TestIAMPolicyResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"-\n" +
	"\x15LookupIdentityRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"v\n" +
	"\x16LookupIdentityResponse\x12'\n" +
	"\x0fservice_account\x18\x01 \x01(\tR\x0eserviceAccount\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"7\n" +
	"\n" +
	"KMSRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"!\n" +
	"\vKMSResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"?\n" +
	"\x0eKMSSignRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"/\n" +
	"\x0fKMSSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"M\n" +
	"\x0eDBTokenRequest\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"S\n" +
	"\x0fDBTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x03R\texpiresIn\"\x93\x01\n" +
	"\x12ImpersonateRequest\x12/\n" +
	"\x13instigator_identity\x18\x01 \x01(\tR\x12instigatorIdentity\x124\n" +
	"\x16target_service_account\x18\x02 \x01(\tR\x14targetServiceAccount\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes2\xd2\b\n" +
	"\x11FoundationService\x12^\n" +
	"\tVaultRead\x12'.olympus.foundation.v1.VaultReadRequest\x1a(.olympus.foundation.v1.VaultReadResponse\x12a\n" +
	"\n" +
	"VaultWrite\x12(.olympus.foundation.v1.VaultWriteRequest\x1a).olympus.foundation.v1.VaultWriteResponse\x12a\n" +
	"\n" +
	"CreateUser\x12(.olympus.foundation.v1.CreateUserRequest\x1a).olympus.foundation.v1.CreateUserResponse\x12d\n" +
	"\vVerifyToken\x12).olympus.foundation.v1.VerifyTokenRequest\x1a*.olympus.foundation.v1.VerifyTokenResponse\x12j\n" +
	"\rTestIAMPolicy\x12+.olympus.foundation.v1.TestIAMPolicyRequest\x1a,.olympus.foundation.v1.TestIAMPolicyResponse\x12m\n" +
	"\x0eLookupIdentity\x12,.olympus.foundation.v1.LookupIdentityRequest\x1a-.olympus.foundation.v1.LookupIdentityResponse\x12S\n" +
	"\n" +
	"KMSDecrypt\x12!.olympus.foundation.v1.KMSRequest\x1a\".olympus.foundation.v1.KMSResponse\x12S\n" +
	"\n" +
	"KMSEncrypt\x12!.olympus.foundation.v1.KMSRequest\x1a\".olympus.foundation.v1.KMSResponse\x12X\n" +
	"\aKMSSign\x12%.olympus.foundation.v1.KMSSignRequest\x1a&.olympus.foundation.v1.KMSSignResponse\x12b\n" +
	"\x11MintDatabaseToken\x12%.olympus.foundation.v1.DBTokenRequest\x1a&.olympus.foundation.v1.DBTokenResponse\x12n\n" +
	"\x19ImpersonateServiceAccount\x12).olympus.foundation.v1.ImpersonateRequest\x1a&.olympus.foundation.v1.DBTokenResponseBqZoOlympusGCP-Foundation/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/foundation/v1;foundationv1b\x06proto3"

var (
	file_olympus_foundation_v1_foundation_proto_rawDescOnce sync.Once
	file_olympus_foundation_v1_foundation_proto_rawDescData []byte
)

func file_olympus_foundation_v1_foundation_proto_rawDescGZIP() []byte {
	file_olympus_foundation_v1_foundation_proto_rawDescOnce.Do(func() {
		file_olympus_foundation_v1_foundation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olympus_foundation_v1_foundation_proto_rawDesc), len(file_olympus_foundation_v1_foundation_proto_rawDesc)))
	})
	return file_olympus_foundation_v1_foundation_proto_rawDescData
}

var file_olympus_foundation_v1_foundation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_olympus_foundation_v1_foundation_proto_goTypes = []any{
	(*VaultReadRequest)(nil),       // 0: olympus.foundation.v1.VaultReadRequest
	(*VaultReadResponse)(nil),      // 1: olympus.foundation.v1.VaultReadResponse
	(*VaultWriteRequest)(nil),      // 2: olympus.foundation.v1.VaultWriteRequest
	(*VaultWriteResponse)(nil),     // 3: olympus.foundation.v1.VaultWriteResponse
	(*CreateUserRequest)(nil),      // 4: olympus.foundation.v1.CreateUserRequest
	(*CreateUserResponse)(nil),     // 5: olympus.foundation.v1.CreateUserResponse
	(*VerifyTokenRequest)(nil),     // 6: olympus.foundation.v1.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),    // 7: olympus.foundation.v1.VerifyTokenResponse
	(*TestIAMPolicyRequest)(nil),   // 8: olympus.foundation.v1.TestIAMPolicyRequest
	(*TestIAMPolicyResponse)(nil),  // 9: olympus.foundation.v1.TestIAMPolicyResponse
	(*LookupIdentityRequest)(nil),  // 10: olympus.foundation.v1.LookupIdentityRequest
	(*LookupIdentityResponse)(nil), // 11: olympus.foundation.v1.LookupIdentityResponse
	(*KMSRequest)(nil),             // 12: olympus.foundation.v1.KMSRequest
	(*KMSResponse)(nil),            // 13: olympus.foundation.v1.KMSResponse
	(*KMSSignRequest)(nil),         // 14: olympus.foundation.v1.KMSSignRequest
	(*KMSSignResponse)(nil),        // 15: olympus.foundation.v1.KMSSignResponse
	(*DBTokenRequest)(nil),         // 16: olympus.foundation.v1.DBTokenRequest
	(*DBTokenResponse)(nil),        // 17: olympus.foundation.v1.DBTokenResponse
	(*ImpersonateRequest)(nil),     // 18: olympus.foundation.v1.ImpersonateRequest
}
var file_olympus_foundation_v1_foundation_proto_depIdxs = []int32{
	0,  // 0: olympus.foundation.v1.FoundationService.VaultRead:input_type -> olympus.foundation.v1.VaultReadRequest
	2,  // 1: olympus.foundation.v1.FoundationService.VaultWrite:input_type -> olympus.foundation.v1.VaultWriteRequest
	4,  // 2: olympus.foundation.v1.FoundationService.CreateUser:input_type -> olympus.foundation.v1.CreateUserRequest
	6,  // 3: olympus.foundation.v1.FoundationService.VerifyToken:input_type -> olympus.foundation.v1.VerifyTokenRequest
	8,  // 4: olympus.foundation.v1.FoundationService.TestIAMPolicy:input_type -> olympus.foundation.v1.TestIAMPolicyRequest
	10, // 5: olympus.foundation.v1.FoundationService.LookupIdentity:input_type -> olympus.foundation.v1.LookupIdentityRequest
	12, // 6: olympus.foundation.v1.FoundationService.KMSDecrypt:input_type -> olympus.foundation.v1.KMSRequest
	12, // 7: olympus.foundation.v1.FoundationService.KMSEncrypt:input_type -> olympus.foundation.v1.KMSRequest
	14, // 8: olympus.foundation.v1.FoundationService.KMSSign:input_type -> olympus.foundation.v1.KMSSignRequest
	16, // 9: olympus.foundation.v1.FoundationService.MintDatabaseToken:input_type -> olympus.foundation.v1.DBTokenRequest
	18, // 10: olympus.foundation.v1.FoundationService.ImpersonateServiceAccount:input_type -> olympus.foundation.v1.ImpersonateRequest
	1,  // 11: olympus.foundation.v1.FoundationService.VaultRead:output_type -> olympus.foundation.v1.VaultReadResponse
	3,  // 12: olympus.foundation.v1.FoundationService.VaultWrite:output_type -> olympus.foundation.v1.VaultWriteResponse
	5,  // 13: olympus.foundation.v1.FoundationService.CreateUser:output_type -> olympus.foundation.v1.CreateUserResponse
	7,  // 14: olympus.foundation.v1.FoundationService.VerifyToken:output_type -> olympus.foundation.v1.VerifyTokenResponse
	9,  // 15: olympus.foundation.v1.FoundationService.TestIAMPolicy:output_type -> olympus.foundation.v1.TestIAMPolicyResponse
	11, // 16: olympus.foundation.v1.FoundationService.LookupIdentity:output_type -> olympus.foundation.v1.LookupIdentityResponse
	13, // 17: olympus.foundation.v1.FoundationService.KMSDecrypt:output_type -> olympus.foundation.v1.KMSResponse
	13, // 18: olympus.foundation.v1.FoundationService.KMSEncrypt:output_type -> olympus.foundation.v1.KMSResponse
	15, // 19: olympus.foundation.v1.FoundationService.KMSSign:output_type -> olympus.foundation.v1.KMSSignResponse
	17, // 20: olympus.foundation.v1.FoundationService.MintDatabaseToken:output_type -> olympus.foundation.v1.DBTokenResponse
	17, // 21: olympus.foundation.v1.FoundationService.ImpersonateServiceAccount:output_type -> olympus.foundation.v1.DBTokenResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_olympus_foundation_v1_foundation_proto_init() }
func file_olympus_foundation_v1_foundation_proto_init() {
	if File_olympus_foundation_v1_foundation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olympus_foundation_v1_foundation_proto_rawDesc), len(file_olympus_foundation_v1_foundation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olympus_foundation_v1_foundation_proto_goTypes,
		DependencyIndexes: file_olympus_foundation_v1_foundation_proto_depIdxs,
		MessageInfos:      file_olympus_foundation_v1_foundation_proto_msgTypes,
	}.Build()
	File_olympus_foundation_v1_foundation_proto = out.File
	file_olympus_foundation_v1_foundation_proto_goTypes = nil
	file_olympus_foundation_v1_foundation_proto_depIdxs = nil
}
