// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: olympus/foundation/v1/foundation.proto

package foundationv1connect

import (
	v1 "OlympusGCP-Foundation/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/foundation/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FoundationServiceName is the fully-qualified name of the FoundationService service.
	FoundationServiceName = "olympus.foundation.v1.FoundationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FoundationServiceVaultReadProcedure is the fully-qualified name of the FoundationService's
	// VaultRead RPC.
	FoundationServiceVaultReadProcedure = "/olympus.foundation.v1.FoundationService/VaultRead"
	// FoundationServiceVaultWriteProcedure is the fully-qualified name of the FoundationService's
	// VaultWrite RPC.
	FoundationServiceVaultWriteProcedure = "/olympus.foundation.v1.FoundationService/VaultWrite"
	// FoundationServiceCreateUserProcedure is the fully-qualified name of the FoundationService's
	// CreateUser RPC.
	FoundationServiceCreateUserProcedure = "/olympus.foundation.v1.FoundationService/CreateUser"
	// FoundationServiceVerifyTokenProcedure is the fully-qualified name of the FoundationService's
	// VerifyToken RPC.
	FoundationServiceVerifyTokenProcedure = "/olympus.foundation.v1.FoundationService/VerifyToken"
	// FoundationServiceTestIAMPolicyProcedure is the fully-qualified name of the FoundationService's
	// TestIAMPolicy RPC.
	FoundationServiceTestIAMPolicyProcedure = "/olympus.foundation.v1.FoundationService/TestIAMPolicy"
	// FoundationServiceLookupIdentityProcedure is the fully-qualified name of the FoundationService's
	// LookupIdentity RPC.
	FoundationServiceLookupIdentityProcedure = "/olympus.foundation.v1.FoundationService/LookupIdentity"
	// FoundationServiceKMSDecryptProcedure is the fully-qualified name of the FoundationService's
	// KMSDecrypt RPC.
	FoundationServiceKMSDecryptProcedure = "/olympus.foundation.v1.FoundationService/KMSDecrypt"
	// FoundationServiceKMSEncryptProcedure is the fully-qualified name of the FoundationService's
	// KMSEncrypt RPC.
	FoundationServiceKMSEncryptProcedure = "/olympus.foundation.v1.FoundationService/KMSEncrypt"
	// FoundationServiceKMSSignProcedure is the fully-qualified name of the FoundationService's KMSSign
	// RPC.
	FoundationServiceKMSSignProcedure = "/olympus.foundation.v1.FoundationService/KMSSign"
	// FoundationServiceMintDatabaseTokenProcedure is the fully-qualified name of the
	// FoundationService's MintDatabaseToken RPC.
	FoundationServiceMintDatabaseTokenProcedure = "/olympus.foundation.v1.FoundationService/MintDatabaseToken"
	// FoundationServiceImpersonateServiceAccountProcedure is the fully-qualified name of the
	// FoundationService's ImpersonateServiceAccount RPC.
	FoundationServiceImpersonateServiceAccountProcedure = "/olympus.foundation.v1.FoundationService/ImpersonateServiceAccount"
	// FoundationServiceRunServiceProcedure is the fully-qualified name of the FoundationService's
	// RunService RPC.
	FoundationServiceRunServiceProcedure = "/olympus.foundation.v1.FoundationService/RunService"
	// FoundationServiceTriggerFunctionProcedure is the fully-qualified name of the FoundationService's
	// TriggerFunction RPC.
	FoundationServiceTriggerFunctionProcedure = "/olympus.foundation.v1.FoundationService/TriggerFunction"
)

// FoundationServiceClient is a client for the olympus.foundation.v1.FoundationService service.
type FoundationServiceClient interface {
	// --- Secret Manager (Vault) ---
	VaultRead(context.Context, *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error)
	VaultWrite(context.Context, *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error)
	// --- Identity Platform (Firebase Auth) ---
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	VerifyToken(context.Context, *connect.Request[v1.VerifyTokenRequest]) (*connect.Response[v1.VerifyTokenResponse], error)
	// --- Cloud IAM ---
	TestIAMPolicy(context.Context, *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error)
	LookupIdentity(context.Context, *connect.Request[v1.LookupIdentityRequest]) (*connect.Response[v1.LookupIdentityResponse], error)
	// --- Cloud KMS (Expansion) ---
	KMSDecrypt(context.Context, *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error)
	KMSEncrypt(context.Context, *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error)
	KMSSign(context.Context, *connect.Request[v1.KMSSignRequest]) (*connect.Response[v1.KMSSignResponse], error)
	// --- Database Auth (Deepening) ---
	MintDatabaseToken(context.Context, *connect.Request[v1.DBTokenRequest]) (*connect.Response[v1.DBTokenResponse], error)
	// --- Workload Identity (Expansion) ---
	ImpersonateServiceAccount(context.Context, *connect.Request[v1.ImpersonateRequest]) (*connect.Response[v1.DBTokenResponse], error)
	// --- Cloud Run / Compute (Consolidation) ---
	RunService(context.Context, *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error)
	TriggerFunction(context.Context, *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error)
}

// NewFoundationServiceClient constructs a client for the olympus.foundation.v1.FoundationService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFoundationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FoundationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	foundationServiceMethods := v1.File_olympus_foundation_v1_foundation_proto.Services().ByName("FoundationService").Methods()
	return &foundationServiceClient{
		vaultRead: connect.NewClient[v1.VaultReadRequest, v1.VaultReadResponse](
			httpClient,
			baseURL+FoundationServiceVaultReadProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("VaultRead")),
			connect.WithClientOptions(opts...),
		),
		vaultWrite: connect.NewClient[v1.VaultWriteRequest, v1.VaultWriteResponse](
			httpClient,
			baseURL+FoundationServiceVaultWriteProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("VaultWrite")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+FoundationServiceCreateUserProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		verifyToken: connect.NewClient[v1.VerifyTokenRequest, v1.VerifyTokenResponse](
			httpClient,
			baseURL+FoundationServiceVerifyTokenProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("VerifyToken")),
			connect.WithClientOptions(opts...),
		),
		testIAMPolicy: connect.NewClient[v1.TestIAMPolicyRequest, v1.TestIAMPolicyResponse](
			httpClient,
			baseURL+FoundationServiceTestIAMPolicyProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("TestIAMPolicy")),
			connect.WithClientOptions(opts...),
		),
		lookupIdentity: connect.NewClient[v1.LookupIdentityRequest, v1.LookupIdentityResponse](
			httpClient,
			baseURL+FoundationServiceLookupIdentityProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("LookupIdentity")),
			connect.WithClientOptions(opts...),
		),
		kMSDecrypt: connect.NewClient[v1.KMSRequest, v1.KMSResponse](
			httpClient,
			baseURL+FoundationServiceKMSDecryptProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("KMSDecrypt")),
			connect.WithClientOptions(opts...),
		),
		kMSEncrypt: connect.NewClient[v1.KMSRequest, v1.KMSResponse](
			httpClient,
			baseURL+FoundationServiceKMSEncryptProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("KMSEncrypt")),
			connect.WithClientOptions(opts...),
		),
		kMSSign: connect.NewClient[v1.KMSSignRequest, v1.KMSSignResponse](
			httpClient,
			baseURL+FoundationServiceKMSSignProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("KMSSign")),
			connect.WithClientOptions(opts...),
		),
		mintDatabaseToken: connect.NewClient[v1.DBTokenRequest, v1.DBTokenResponse](
			httpClient,
			baseURL+FoundationServiceMintDatabaseTokenProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("MintDatabaseToken")),
			connect.WithClientOptions(opts...),
		),
		impersonateServiceAccount: connect.NewClient[v1.ImpersonateRequest, v1.DBTokenResponse](
			httpClient,
			baseURL+FoundationServiceImpersonateServiceAccountProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("ImpersonateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		runService: connect.NewClient[v1.RunServiceRequest, v1.RunServiceResponse](
			httpClient,
			baseURL+FoundationServiceRunServiceProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("RunService")),
			connect.WithClientOptions(opts...),
		),
		triggerFunction: connect.NewClient[v1.TriggerFunctionRequest, v1.TriggerFunctionResponse](
			httpClient,
			baseURL+FoundationServiceTriggerFunctionProcedure,
			connect.WithSchema(foundationServiceMethods.ByName("TriggerFunction")),
			connect.WithClientOptions(opts...),
		),
	}
}

// foundationServiceClient implements FoundationServiceClient.
type foundationServiceClient struct {
	vaultRead                 *connect.Client[v1.VaultReadRequest, v1.VaultReadResponse]
	vaultWrite                *connect.Client[v1.VaultWriteRequest, v1.VaultWriteResponse]
	createUser                *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	verifyToken               *connect.Client[v1.VerifyTokenRequest, v1.VerifyTokenResponse]
	testIAMPolicy             *connect.Client[v1.TestIAMPolicyRequest, v1.TestIAMPolicyResponse]
	lookupIdentity            *connect.Client[v1.LookupIdentityRequest, v1.LookupIdentityResponse]
	kMSDecrypt                *connect.Client[v1.KMSRequest, v1.KMSResponse]
	kMSEncrypt                *connect.Client[v1.KMSRequest, v1.KMSResponse]
	kMSSign                   *connect.Client[v1.KMSSignRequest, v1.KMSSignResponse]
	mintDatabaseToken         *connect.Client[v1.DBTokenRequest, v1.DBTokenResponse]
	impersonateServiceAccount *connect.Client[v1.ImpersonateRequest, v1.DBTokenResponse]
	runService                *connect.Client[v1.RunServiceRequest, v1.RunServiceResponse]
	triggerFunction           *connect.Client[v1.TriggerFunctionRequest, v1.TriggerFunctionResponse]
}

// VaultRead calls olympus.foundation.v1.FoundationService.VaultRead.
func (c *foundationServiceClient) VaultRead(ctx context.Context, req *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error) {
	return c.vaultRead.CallUnary(ctx, req)
}

// VaultWrite calls olympus.foundation.v1.FoundationService.VaultWrite.
func (c *foundationServiceClient) VaultWrite(ctx context.Context, req *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error) {
	return c.vaultWrite.CallUnary(ctx, req)
}

// CreateUser calls olympus.foundation.v1.FoundationService.CreateUser.
func (c *foundationServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// VerifyToken calls olympus.foundation.v1.FoundationService.VerifyToken.
func (c *foundationServiceClient) VerifyToken(ctx context.Context, req *connect.Request[v1.VerifyTokenRequest]) (*connect.Response[v1.VerifyTokenResponse], error) {
	return c.verifyToken.CallUnary(ctx, req)
}

// TestIAMPolicy calls olympus.foundation.v1.FoundationService.TestIAMPolicy.
func (c *foundationServiceClient) TestIAMPolicy(ctx context.Context, req *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error) {
	return c.testIAMPolicy.CallUnary(ctx, req)
}

// LookupIdentity calls olympus.foundation.v1.FoundationService.LookupIdentity.
func (c *foundationServiceClient) LookupIdentity(ctx context.Context, req *connect.Request[v1.LookupIdentityRequest]) (*connect.Response[v1.LookupIdentityResponse], error) {
	return c.lookupIdentity.CallUnary(ctx, req)
}

// KMSDecrypt calls olympus.foundation.v1.FoundationService.KMSDecrypt.
func (c *foundationServiceClient) KMSDecrypt(ctx context.Context, req *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error) {
	return c.kMSDecrypt.CallUnary(ctx, req)
}

// KMSEncrypt calls olympus.foundation.v1.FoundationService.KMSEncrypt.
func (c *foundationServiceClient) KMSEncrypt(ctx context.Context, req *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error) {
	return c.kMSEncrypt.CallUnary(ctx, req)
}

// KMSSign calls olympus.foundation.v1.FoundationService.KMSSign.
func (c *foundationServiceClient) KMSSign(ctx context.Context, req *connect.Request[v1.KMSSignRequest]) (*connect.Response[v1.KMSSignResponse], error) {
	return c.kMSSign.CallUnary(ctx, req)
}

// MintDatabaseToken calls olympus.foundation.v1.FoundationService.MintDatabaseToken.
func (c *foundationServiceClient) MintDatabaseToken(ctx context.Context, req *connect.Request[v1.DBTokenRequest]) (*connect.Response[v1.DBTokenResponse], error) {
	return c.mintDatabaseToken.CallUnary(ctx, req)
}

// ImpersonateServiceAccount calls
// olympus.foundation.v1.FoundationService.ImpersonateServiceAccount.
func (c *foundationServiceClient) ImpersonateServiceAccount(ctx context.Context, req *connect.Request[v1.ImpersonateRequest]) (*connect.Response[v1.DBTokenResponse], error) {
	return c.impersonateServiceAccount.CallUnary(ctx, req)
}

// RunService calls olympus.foundation.v1.FoundationService.RunService.
func (c *foundationServiceClient) RunService(ctx context.Context, req *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error) {
	return c.runService.CallUnary(ctx, req)
}

// TriggerFunction calls olympus.foundation.v1.FoundationService.TriggerFunction.
func (c *foundationServiceClient) TriggerFunction(ctx context.Context, req *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error) {
	return c.triggerFunction.CallUnary(ctx, req)
}

// FoundationServiceHandler is an implementation of the olympus.foundation.v1.FoundationService
// service.
type FoundationServiceHandler interface {
	// --- Secret Manager (Vault) ---
	VaultRead(context.Context, *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error)
	VaultWrite(context.Context, *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error)
	// --- Identity Platform (Firebase Auth) ---
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	VerifyToken(context.Context, *connect.Request[v1.VerifyTokenRequest]) (*connect.Response[v1.VerifyTokenResponse], error)
	// --- Cloud IAM ---
	TestIAMPolicy(context.Context, *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error)
	LookupIdentity(context.Context, *connect.Request[v1.LookupIdentityRequest]) (*connect.Response[v1.LookupIdentityResponse], error)
	// --- Cloud KMS (Expansion) ---
	KMSDecrypt(context.Context, *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error)
	KMSEncrypt(context.Context, *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error)
	KMSSign(context.Context, *connect.Request[v1.KMSSignRequest]) (*connect.Response[v1.KMSSignResponse], error)
	// --- Database Auth (Deepening) ---
	MintDatabaseToken(context.Context, *connect.Request[v1.DBTokenRequest]) (*connect.Response[v1.DBTokenResponse], error)
	// --- Workload Identity (Expansion) ---
	ImpersonateServiceAccount(context.Context, *connect.Request[v1.ImpersonateRequest]) (*connect.Response[v1.DBTokenResponse], error)
	// --- Cloud Run / Compute (Consolidation) ---
	RunService(context.Context, *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error)
	TriggerFunction(context.Context, *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error)
}

// NewFoundationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFoundationServiceHandler(svc FoundationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	foundationServiceMethods := v1.File_olympus_foundation_v1_foundation_proto.Services().ByName("FoundationService").Methods()
	foundationServiceVaultReadHandler := connect.NewUnaryHandler(
		FoundationServiceVaultReadProcedure,
		svc.VaultRead,
		connect.WithSchema(foundationServiceMethods.ByName("VaultRead")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceVaultWriteHandler := connect.NewUnaryHandler(
		FoundationServiceVaultWriteProcedure,
		svc.VaultWrite,
		connect.WithSchema(foundationServiceMethods.ByName("VaultWrite")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceCreateUserHandler := connect.NewUnaryHandler(
		FoundationServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(foundationServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceVerifyTokenHandler := connect.NewUnaryHandler(
		FoundationServiceVerifyTokenProcedure,
		svc.VerifyToken,
		connect.WithSchema(foundationServiceMethods.ByName("VerifyToken")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceTestIAMPolicyHandler := connect.NewUnaryHandler(
		FoundationServiceTestIAMPolicyProcedure,
		svc.TestIAMPolicy,
		connect.WithSchema(foundationServiceMethods.ByName("TestIAMPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceLookupIdentityHandler := connect.NewUnaryHandler(
		FoundationServiceLookupIdentityProcedure,
		svc.LookupIdentity,
		connect.WithSchema(foundationServiceMethods.ByName("LookupIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceKMSDecryptHandler := connect.NewUnaryHandler(
		FoundationServiceKMSDecryptProcedure,
		svc.KMSDecrypt,
		connect.WithSchema(foundationServiceMethods.ByName("KMSDecrypt")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceKMSEncryptHandler := connect.NewUnaryHandler(
		FoundationServiceKMSEncryptProcedure,
		svc.KMSEncrypt,
		connect.WithSchema(foundationServiceMethods.ByName("KMSEncrypt")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceKMSSignHandler := connect.NewUnaryHandler(
		FoundationServiceKMSSignProcedure,
		svc.KMSSign,
		connect.WithSchema(foundationServiceMethods.ByName("KMSSign")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceMintDatabaseTokenHandler := connect.NewUnaryHandler(
		FoundationServiceMintDatabaseTokenProcedure,
		svc.MintDatabaseToken,
		connect.WithSchema(foundationServiceMethods.ByName("MintDatabaseToken")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceImpersonateServiceAccountHandler := connect.NewUnaryHandler(
		FoundationServiceImpersonateServiceAccountProcedure,
		svc.ImpersonateServiceAccount,
		connect.WithSchema(foundationServiceMethods.ByName("ImpersonateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceRunServiceHandler := connect.NewUnaryHandler(
		FoundationServiceRunServiceProcedure,
		svc.RunService,
		connect.WithSchema(foundationServiceMethods.ByName("RunService")),
		connect.WithHandlerOptions(opts...),
	)
	foundationServiceTriggerFunctionHandler := connect.NewUnaryHandler(
		FoundationServiceTriggerFunctionProcedure,
		svc.TriggerFunction,
		connect.WithSchema(foundationServiceMethods.ByName("TriggerFunction")),
		connect.WithHandlerOptions(opts...),
	)
	return "/olympus.foundation.v1.FoundationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FoundationServiceVaultReadProcedure:
			foundationServiceVaultReadHandler.ServeHTTP(w, r)
		case FoundationServiceVaultWriteProcedure:
			foundationServiceVaultWriteHandler.ServeHTTP(w, r)
		case FoundationServiceCreateUserProcedure:
			foundationServiceCreateUserHandler.ServeHTTP(w, r)
		case FoundationServiceVerifyTokenProcedure:
			foundationServiceVerifyTokenHandler.ServeHTTP(w, r)
		case FoundationServiceTestIAMPolicyProcedure:
			foundationServiceTestIAMPolicyHandler.ServeHTTP(w, r)
		case FoundationServiceLookupIdentityProcedure:
			foundationServiceLookupIdentityHandler.ServeHTTP(w, r)
		case FoundationServiceKMSDecryptProcedure:
			foundationServiceKMSDecryptHandler.ServeHTTP(w, r)
		case FoundationServiceKMSEncryptProcedure:
			foundationServiceKMSEncryptHandler.ServeHTTP(w, r)
		case FoundationServiceKMSSignProcedure:
			foundationServiceKMSSignHandler.ServeHTTP(w, r)
		case FoundationServiceMintDatabaseTokenProcedure:
			foundationServiceMintDatabaseTokenHandler.ServeHTTP(w, r)
		case FoundationServiceImpersonateServiceAccountProcedure:
			foundationServiceImpersonateServiceAccountHandler.ServeHTTP(w, r)
		case FoundationServiceRunServiceProcedure:
			foundationServiceRunServiceHandler.ServeHTTP(w, r)
		case FoundationServiceTriggerFunctionProcedure:
			foundationServiceTriggerFunctionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFoundationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFoundationServiceHandler struct{}

func (UnimplementedFoundationServiceHandler) VaultRead(context.Context, *connect.Request[v1.VaultReadRequest]) (*connect.Response[v1.VaultReadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.VaultRead is not implemented"))
}

func (UnimplementedFoundationServiceHandler) VaultWrite(context.Context, *connect.Request[v1.VaultWriteRequest]) (*connect.Response[v1.VaultWriteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.VaultWrite is not implemented"))
}

func (UnimplementedFoundationServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.CreateUser is not implemented"))
}

func (UnimplementedFoundationServiceHandler) VerifyToken(context.Context, *connect.Request[v1.VerifyTokenRequest]) (*connect.Response[v1.VerifyTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.VerifyToken is not implemented"))
}

func (UnimplementedFoundationServiceHandler) TestIAMPolicy(context.Context, *connect.Request[v1.TestIAMPolicyRequest]) (*connect.Response[v1.TestIAMPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.TestIAMPolicy is not implemented"))
}

func (UnimplementedFoundationServiceHandler) LookupIdentity(context.Context, *connect.Request[v1.LookupIdentityRequest]) (*connect.Response[v1.LookupIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.LookupIdentity is not implemented"))
}

func (UnimplementedFoundationServiceHandler) KMSDecrypt(context.Context, *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.KMSDecrypt is not implemented"))
}

func (UnimplementedFoundationServiceHandler) KMSEncrypt(context.Context, *connect.Request[v1.KMSRequest]) (*connect.Response[v1.KMSResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.KMSEncrypt is not implemented"))
}

func (UnimplementedFoundationServiceHandler) KMSSign(context.Context, *connect.Request[v1.KMSSignRequest]) (*connect.Response[v1.KMSSignResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.KMSSign is not implemented"))
}

func (UnimplementedFoundationServiceHandler) MintDatabaseToken(context.Context, *connect.Request[v1.DBTokenRequest]) (*connect.Response[v1.DBTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.MintDatabaseToken is not implemented"))
}

func (UnimplementedFoundationServiceHandler) ImpersonateServiceAccount(context.Context, *connect.Request[v1.ImpersonateRequest]) (*connect.Response[v1.DBTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.ImpersonateServiceAccount is not implemented"))
}

func (UnimplementedFoundationServiceHandler) RunService(context.Context, *connect.Request[v1.RunServiceRequest]) (*connect.Response[v1.RunServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.RunService is not implemented"))
}

func (UnimplementedFoundationServiceHandler) TriggerFunction(context.Context, *connect.Request[v1.TriggerFunctionRequest]) (*connect.Response[v1.TriggerFunctionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.foundation.v1.FoundationService.TriggerFunction is not implemented"))
}
